"""second Migration

Revision ID: 31de6e205300
Revises: aaae01e67f97
Create Date: 2019-09-21 19:40:08.910437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31de6e205300'
down_revision = 'aaae01e67f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photoprofiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photoprofiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='photoprofiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photoprofiles_pkey')
    )
    # ### end Alembic commands ###
