"""five Migration

Revision ID: 659513124805
Revises: d52bcbc4f8ac
Create Date: 2019-09-24 16:02:51.999109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659513124805'
down_revision = 'd52bcbc4f8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
