"""seventh Migration

Revision ID: e3970915be77
Revises: 659513124805
Create Date: 2019-09-24 16:26:07.984312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3970915be77'
down_revision = '659513124805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'feedback')
    # ### end Alembic commands ###
